version: "2"
services:
  app:
    build: ./
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql/mysql-server:latest
    ports:
      - "33061:3306"
    environment:
            MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
            MYSQL_ROOT_HOST: "${HOST}"
            MYSQL_DATABASE: '${DATABASE_NAME}'
            MYSQL_USER: '${DATABASE_USERNAME}'
            MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
